### ISSUE TITLE
Convert id identification for divs to classes

### ISSUE THREAD

**Issue by DennieCodes** [ltgoodworth/recipe-page-main#1]
Hey Lee,

One thing that I noticed that I would like for you to look at it refactoring your project from using Id's to apply styling to divs, and instead use classes.  Here is a good article that goes over why: [Type Class and Id Selectors](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Type_Class_and_ID_Selectors)

**Comment by ltgoodworth** [comment]
Issue resolved with refactor branch. Merged with master
